/*
 * This source file was generated by the Gradle 'init' task
 */
package test2;
import java.util.Scanner;
public class App {
    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);
        System.out.println("enter N: ");
        int Number = scanIn.nextInt();

        for (int i = 0; i < Number;i++){
            for(int j = 0; j < Number;j++){
                System.out.print("* ");
            }
            System.out.println();
        }
    }
}
