/*
 * This source file was generated by the Gradle 'init' task
 */
package test4;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
public class App {
    public static void main(String[] args) {
    Scanner scanIn = new Scanner(System.in);
    int[]array = new int[10];
    Set<Integer> num = new HashSet<>();

    System.out.println("Enter 10 integers: ");
    
    for(int i=0; i < 10; i++){
        System.out.print("Integer: " + (i + 1) + ": ");
        array[i] = scanIn.nextInt();
        num.add(array[i]);
    }
        System.out.println("Unique numbers is: ");{
            for(int x : num){
                System.out.println(x + " ");{
                }
            }
        }
    }
}