/*
 * This source file was generated by the Gradle 'init' task
 */
package test5;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
           Scanner scanIn = new Scanner(System.in);

    int[][] matrix = new int[3][3];
    int[][] transpose = new int[3][3];

    System.out.println("Enter values for a 3x3 matrix:");
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            System.out.print("Enter Matrix index of [" + i + "][" + j + "] : ");
            matrix[i][j] = scanIn.nextInt();
        }
    }

    System.out.println("\nNormal Matrix is:");
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            System.out.print(matrix[i][j] + " ");
        }
        System.out.println();
    }
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            transpose[j][i] = matrix[i][j];
        }
    }
    System.out.println("\nMatrix Transpose is:");
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            System.out.print(transpose[i][j] + " ");
        }
        System.out.println();
    }

    scanIn.close();
}
    }

